spring:
  cloud:
    function:
      definition: processor
    stream:
      default:
        producer:
          useNativeEncoding: true
        consumer:
          useNativeDecoding: true
      kafka:
        binder:
          consumer-properties:
            value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            schema.registry.url: http://localhost:8081
          producer-properties:
            value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            key.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            schema.registry.url: http://localhost:8081
      bindings:
        processor-in-0:
          destination: string-input
          content-type: application/*+avro
          group: str-to-int-mapper
          concurrency: 1
        processor-out-0:
          destination: integer-output
          content-type: application/*+avro